# encoding: utf-8
module Kingonomy
  module Fundamentals
    FIELDS = {	
      :adp_100       =>	"Average Daily Price - 100 day",
      :adp_200       => "Average Daily Price - 200 day",
      :adp_50        => "Average Daily Price - 50 day",
      :adv_21        => "Average Daily Volume - 21 day",
      :adv_30        => "Average Daily Volume - 30 day",
      :adv_90        => "Average Daily Volume - 90 day",
      :ask           => "Ask price",
      :ask_time      => "Time of latest ask",
      :asksz         => "Size of latest ask (in 100s)",
      :basis         => "Reported precision (quotation decimal places)",
      :beta          => "Beta volatility measure",
      :bid           => "Bid price",
      :bid_time      => "Time of latest bid",
      :bidsz         => "Size of latest bid (in 100s)",
      :bidtick       => "Tick direction since last bid",
      :chg           => "Change since prior day close (cl)",
      :chg_sign      => "Change sign (e, u, d) as even, up, down",
      :chg_t         => "change in text format",
      :cl            => "previous close",
      :contract_size => "contract size for option",
      :cusip         => "Cusip",
      :date          => "Trade date of last trade",
      :datetime      => "Date and time",
      :div           => "Latest announced cash dividend",
      :divexdate     => "Ex-dividend date of div(YYYYMMDD)",
      :divfreq       => "Dividend frequency, Quarterly, Monthly, Yearly, etc.",
      :divpaydt      => "Dividend pay date of last announced div",
      :dollar_value  => "Total dollar value of shares traded today",
      :eps           => "Earnings per share",
      :exch          => "exchange code",
      :exch_desc     => "exchange description",
      :hi            => "High Trade Price for the trading day",
      :iad           => "Indicated annual dividend",
      :incr_vl       => "Volume of last trade",
      :last          => "Last trade price",
      :lo            => "Low Trade Price for the trading day",
      :name          => "Company name",
      :op_flag       => "Security has options (1=Yes, 0=No).",
      :opn           => "Open trade price",
      :pchg          => "percentage change from prior day close",
      :pchg_sign     => "pchg sign, 'u'for up, 'd'for down",
      :pcls          => "Prior day close",
      :pe            => "Price earnings ratio",
      :phi           => "Prior day high value",
      :plo           => "Prior day low value",
      :popn          => "Prior day open",
      :pr_adp_100    => "Prior Average Daily Price '100' trade days",
      :pr_adp_200    => "Prior Average Daily Price '200' trade days",
      :pr_adp_50     => "Prior Average Daily Price '50' trade days",
      :pr_date       => "Trade Date of Prior Last",
      :prbook        => "Book Value Price",
      :prchg         => "Prior day change",
      :pvol          => "Prior day total volume",
      :qcond         => "Condition code of quote",
      :secclass      => "Security class (0=stock, 1=option)",
      :sesn          => "Trading session as (pre, regular, &amp, post)",
      :sesn_vl       => "Trading session as (pre, regular, &amp, post)",
      :sho           => "Shares Outstanding",
      :symbol        => "Symbol from data provider",
      :tcond         => "Trade condition code – (H) halted or (R) resumed",
      :timestamp     => "Timestamp",
      :tr_num        => "Number of trades since market open",
      :tradetick     => "Tick direction from prior trade – (e,u,d) even, up, down)",
      :trend         => "Trend based on 10 prior ticks (e,u,d) even, up, down",
      :vl            => "Cumulative volume",
      :volatility12  => "one year volatility measure",
      :vwap          => "Volume weighted average price",
      :wk52hi        => "52 week high",
      :wk52hidate    => "52 week high date",
      :wk52lo        => "52 week low",
      :wk52lodate    => "52 week low date",
      :yield         => "Dividend yield as %"
    }
  end
end
